### ISSUE TITLE
Not using system fonts?

### ISSUE THREAD

**Issue by mmetak** [soramimi/SkyMPC#1]
Hi. As you can see on the screenshot skympc (left window) is not using the right font which is set with qt5ct (right window). Other qt5 apps all use the right font.
<a href='https://postimg.org/image/46cw5iown/' target='_blank'><img src='https://s23.postimg.org/46cw5iown/scr.png' border='0' alt='postimage'/></a>

btw I also maintain 'skympc-git' package in AUR for archlinux. ;-)

**Comment by soramimi** [comment]
Please check the function 'QString BasicMainWindow::makeStyleSheetText()', it changes fonts. On linux, fonts is set to 'VL PGothic'. This is best for Japanese, but it may not be the case in other languages. Especially, the code 's += "* {%1;}";' is affects all fonts used in the program. If you remove it, it may be displayed in your favorite font.

**Comment by mmetak** [comment]
Thanks, it works/looks fine as far I can tell. I'll apply a patch to remove that line.
