### ISSUE TITLE
Volume change is not supported

### ISSUE THREAD

**Issue by noobi0** [soramimi/SkyMPC#4]
As sometimes I am forced to use Windows, I like to control mpd via application, and between Chimney (requires MS Store), QMPD, Cantata and Auremo, this client seems to eat least memory, but most importantly it most stable client, as others seem to hung on different ocassions, not only in cases connection to mpd daemon is lost. Hovever rest of the clients support "setvol" option, what is volume control, not SkyMPC. Volume change is also suported under Linex'es and Android apps, so its solely software implementation. Same is when using ALSA or PULSE.

```
audio_output {
type                    "alsa"
name                    "DAC02"
mixer_control           "PCM"
auto_resample           "no"
auto_channels           "no"
auto_format             "no"
}
```

**Comment by soramimi** [comment]
What kind of sound card do you use?
If you know, please tell me the chipset of your sound card.

**Comment by noobi0** [comment]
Its a rather cheap Behringer external USB DAC, UCA202:
```
$ cat /proc/asound/cards
 0 [Audio          ]: Built-in_Audio - Built-in Audio
                      Built-in Audio
 1 [CODEC          ]: USB-Audio - USB Audio CODEC
                      Burr-Brown from TI USB Audio CODEC at usb-s5p-ehci-3.1.2, full speed
```
```
$ lsusb | grep PCM2902
Bus 001 Device 007: ID 08bb:2902 Texas Instruments PCM2902 Audio Codec
```

**Comment by soramimi** [comment]
Sorry, I have no idea.
I checked TI's PCM2704 USB DAC and TENOR's TE7022L USB DAC.
These DACs succeeded volume control.
However, It is true that some sound device is not supported volume control.

**Comment by noobi0** [comment]
Apologies for rising this issue as in connection with this software.
It was MPD issue, and trivial to fix (incorrect mixer type and /dev/snd permissions), just adding comment, as this DAC is very popular:
```
audio_output {
type                    "alsa"
name                    "UCA202"
mixer_control           "Master"
auto_resample           "no"
auto_channels           "no"
auto_format             "no"
use_mmap                "yes"
mixer_type              "hardware"
}
```
One can also change permissions on /dev/snd (if applicable):
`chmod -R a+rw /dev/snd`
